name: pipelines
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=2.4.1
  - holoviews=1.14.6
  - hvplot=0.7.3
  - jupyterlab=3.1.13
  - matplotlib=3.4.3
  - notebook=6.4.4
  - numpy=1.21.2
  - pandas=1.3.3
  - panel=0.12.3
  - pip=21.2.4
  - graphviz
  - python-graphviz
  - python=3.9.7
  - pyviz_comms=2.1.0
  - sqlite=3.36.0
  - statsmodels=0.13.1
  - yaml=0.2.5
  - pip:
    - dask==2021.9.1
    - prefect==0.15.9
    - pyarrow==6.0.0
    - streamlit==1.2.0
    - scikit-learn
    - xgboost
    - lightgbm
    - catboost
    - 'dvc[gdrive]'